version: "3.8"

services:
  mariadb:
    image: mariadb:10.7
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project
      MYSQL_USER: simon
      MYSQL_PASSWORD: simon
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - backend

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  airflow-webserver:
    build: ./airflow
    image: custom-airflow
    container_name: airflow_webserver
    restart: always
    depends_on:
      - mariadb
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+pymysql://simon:simon@mariadb:3306/project
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./.env:/opt/airflow/.env
      - ./data:/opt/airflow/data
    ports:
      - "8080:8080"
    command: webserver
    networks:
      - backend
      - default

  airflow-scheduler:
    build: ./airflow
    image: custom-airflow
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+pymysql://simon:simon@mariadb:3306/project
      AIRFLOW__CORE__FERNET_KEY: ''
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./.env:/opt/airflow/.env
      - ./data:/opt/airflow/data
    command: scheduler
    networks:
      - backend
      - default

  gx:
    build: ./gx
    container_name: gx_validator
    working_dir: /app
    volumes:
      - ./gx:/app
    networks:
      - backend

  streamlit:
    build: ./streamlit_app
    container_name: streamlit_dashboard
    ports:
      - "8501:8501"
    depends_on:
      - redis
    volumes:
      - ./kafka:/opt/kafka
      - ./streamlit_app:/app
    networks:
      - backend


  kafka_consumer:
    build: ./kafka
    container_name: kafka_consumer
    depends_on:
      - kafka
      - redis
    networks:
      - backend


volumes:
  mariadb_data:

networks:
  backend:
    driver: bridge
